#!/bin/sh

remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha; do
	if [ -z "${local_ref##refs/heads/_*}" ]; then
		echo "Are you sure you want to push ${local_ref##refs/heads/} to ${url}?"
		exit 1
	fi
done
