#!/bin/sh
# shell startup

# uncomment to debug shell startup, then run zprof at first interpreter prompt
#[ -n "$ZSH_VERSION" ] && zmodload zsh/zprof

# respect XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CACHE_HOME="$HOME/.cache"
#export XDG_RUNTIME_DIR="$HOME/$TMPDIR"

# prefer locally built packages
export PATH="$HOME/.built/bin:$HOME/dev/go/bin:$HOME/go/bin:$PATH"

source "$XDG_CONFIG_HOME/bash/system"
source "$XDG_CONFIG_HOME/bash/initcommands"
source "$XDG_CONFIG_HOME/bash/functions"
source "$XDG_CONFIG_HOME/bash/aliases"

# automatically configure hooks for the config files themselves
git config -f "$XDG_CONFIG_HOME/.git/config" core.hooksPath git/hooks

# kasugano colors for linux console
if [ "$TERM" = "linux" ]; then
  #\e]P03d3d3d
  /bin/echo -e "
  \e]P0000000
  \e]P16673bf
  \e]P23ea290
  \e]P3b0ead9
  \e]P431658c
  \e]P5596196
  \e]P68292b2
  \e]P7c8cacc
  \e]P84d4d4d
  \e]P9899aff
  \e]PA52ad91
  \e]PB98c9bb
  \e]PC477ab3
  \e]PD7882bf
  \e]PE95a7cc
  \e]PFedeff2
  "
  # get rid of artifacts
  clear
fi

if tty -s; then
  if [ -z "$DISPLAY" ] && [ "$(tty)" != /dev/tty6 ]; then
    if [ "$START_SWAY" = true ] && ! pgrep -u "$UID" sway; then
      sway
      exit
    elif [ "$START_X" = true ]; then
      startx "$XDG_CONFIG_HOME/Xorg/xinitrc"
      exit
    fi
  fi

  # when this feature is enabled, start tmux at every interactive shell
  if [ "$TTY_USE_TMUX" = true ] && [ -z "$TMUX" ]; then

    unset wid
    unset gid
    unset sid

    # when enabled, all tmux windows are connected to the same window group
    if [ "$TTY_TMUX_SHARED" = true ]; then

      # get the first detached session's ID
      gid="$(tmux list-sessions 2>/dev/null | grep -ve '(attached)$' | grep -oe '^[0-9]\+:' | head -n 1)"

      if [ -z "$gid" ]; then
        gid="$(tmux new-session -dP)"
        wid="$gid"
      fi

      # create a new session in that session group
      sid="$(tmux new-session -dPc "$(pwd)" -t "$gid")"

      # create window if we didn't before
      if [ -z "$wid" ]; then
        wid="$(tmux new-window -Pt "$sid")"
      fi

      # don't leave the session open if detached
      (sleep 1; tmux set-option -t "$sid" destroy-unattached on) &

    # otherwise start tmux in the "normal" way, just to give us scrollback and
    # reattach support when windows crash
    else

      # to use .config/bash/initcommand we must start tmux in a subshell
      sid="$(tmux new-session -dP)"

      tmux set-option -t "$sid" status off
    fi

    # attach the session
    exec tmux attach-session -t "$sid"
  fi

  source "$XDG_CONFIG_HOME/bash/prompt"
fi
