#! /bin/sh

sxhkd &
polybar -r bspwm &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           10

bspc config top_padding		10
bspc config bottom_padding	10
bspc config left_padding	10
bspc config right_padding	10

bspc config split_ratio          0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
