#!/bin/bash

# figure out what's installed
command -v feh      >/dev/null 2>&1; feh_status=$?
command -v compton  >/dev/null 2>&1; compton_status=$?
command -v redshift >/dev/null 2>&1; redshift_status=$?
command -v xbanish  >/dev/null 2>&1; xbanish_status=$?

# capslock is backspace
setxkbmap us colemak

# set the wallpaper
xsetroot -solid "#555" # dark gray
if [ $feh_status -eq 0 ]; then
  for wp in /home/qguv/.config/wallpaper.*; do
    feh --bg-fill "$wp"
  done
fi

# dwm status bar
while true; do
  xsetroot -name "$(date '+%a %d %b %H:%M')"
  sleep 5
done &

# window compositor
if [ $compton_status -eq 0 ]; then
  compton -bc --inactive-dim 0.1
fi

# adjust color temperature to time of day
if [ $redshift_status -eq 0 ]; then
  redshift &
fi

# avoid the rodent
if [ $xbanish_status -eq 0 ]; then
  xbanish &
fi

dbus-update-activation-environment --all --systemd

# start dwm
exec dwm
