#!/usr/bin/env bash

# avoid the rodent
xbanish &

# capslock is backspace
xmodmap "$XDG_CONFIG_HOME/Xorg/Xmodmap"
setxkbmap us colemak

# set the wallpaper
xsetroot -solid "#555" # dark gray
for wp in "$XDG_CONFIG_HOME"/wallpaper.*; do
  feh --bg-fill "$wp"
done

# dwm status bar
while true; do
  xsetroot -name "$(date '+%a %d %b %H:%M')"
  sleep 5
done &

compton -bc --inactive-dim 0.1

# start dwm
exec dwm
