#!/bin/bash

# source scripts in /etc/X11/xinit/xinitrc.d/
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# figure out what's installed
command -v feh      >/dev/null 2>&1; feh_status=$?
command -v compton  >/dev/null 2>&1; compton_status=$?
command -v redshift >/dev/null 2>&1; redshift_status=$?
command -v xbanish  >/dev/null 2>&1; xbanish_status=$?
command -v wmname   >/dev/null 2>&1; wmname_status=$?
command -v acpi     >/dev/null 2>&1; acpi_status=$?
command -v loadstat >/dev/null 2>&1; loadstat_status=$?

# disable mouse acceleration
xset m 1 1

# set the wallpaper
if [ $feh_status -eq 0 ]; then
  WPDIR=/usr/share/pixmaps
  feh --bg-fill "$WPDIR/$(ls $WPDIR | grep wallpaper | shuf | head -n 1)"
else
  xsetroot -solid "#333" # dark gray
fi

# dwm status bar
while true; do
  secondary_layout="$(xset -q | grep -A 0 'LED' | cut -c63 | sed 's/1/*/' | sed 's/0//')"

  load=""
  if [ $loadstat_status -eq 0 ]; then
    load="$(loadstat | cut -d' ' -f-3) | "
  fi

  bat=""
  if [[ $acpi_status -eq 0 ]] && [[ "$(acpi -b)" =~ 'harging' ]]; then
    bat="$(acpi -b | cut -f5 -d' ' | cut -f1-2 -d: | tr : h )m | "
  fi

  vpn_off_warning=""
  if [ -z "$(ip addr | grep tun0)" ]; then
    vpn_off_warning=" !!"
  fi

  xsetroot -name "$secondary_layout$vpn_off_warning $load$bat$(date '+%a %d %b %H:%M')"
  sleep 2
done &

# window compositor
if [ $compton_status -eq 0 ]; then
  compton --inactive-dim 0.1 &
fi

# adjust color temperature to time of day
if [ $redshift_status -eq 0 ]; then
  redshift &
fi

# avoid the rodent
if [ $xbanish_status -eq 0 ]; then
  xbanish &
fi

dbus-update-activation-environment --all --systemd

# Java's swing GUI framework is horribly broken
if [ $wmname_status -eq 0 ]; then
  wmname LG3D &
fi
