#!/bin/sh
# a nice banner for nice folks

PUSH_GRAPHIC=$(cat << 'EOF'
                 _              _ _
 _ __  _   _ ___| |__   ___  __| | |
| '_ \| | | / __| '_ \ / _ \/ _` | |
| |_) | |_| \__ | | | |  __| (_| |_|
| .__/ \__,_|___|_| |_|\___|\__,_(_)
|_|
EOF
)

# lolcat colorizes text; is it installed?
command -v lolcat >/dev/null 2>&1; lolcat_status=$?

if [ $lolcat_status -eq 0 ]; then
	printf "$PUSH_GRAPHIC\n\n" | lolcat
else
	printf "$PUSH_GRAPHIC\n\n"
fi

exit 0
