#!/usr/bin/zsh
# zsh custom aliases

# Use system-specific variables
source $XDG_CONFIG_HOME/zsh/system

# UNIX
alias c='clear'
alias s='sudo'
alias la='ls -A'
alias ll='ls -l'
alias lal='ls -Al'
alias lla='ls -Al'
alias unix='date "+%s"'
alias view='vim -R'
alias tgz='tar czvf'
alias detgz='tar xvf'
alias untgz='tar xvf'
alias beep="$BEEPCOMMAND"
alias resolve='cd "$(pwd -P)"'
alias lsaf='find . -type f -exec ls {} \;'

# git
alias g="git"
alias gs="git status -s"
alias gss="git status"
alias gd="git diff"
alias gdc="git diff --cached"

# versioning
alias py='python' # System's default python installation
alias p3="$PYTHON3NAME"
alias p2="$PYTHON2NAME"

# tool functionality
alias ddg="surfraw duckduckgo"
alias tmuxdr="tmux attach || tmux new"

# zsh/functions
alias md='mkdircd'
alias edex='editex'
alias gpa='pushallremotes'

# System tasks
alias reload='source ~/.zshrc'
alias update="$SYSTEMUPDATE"

# Clipboard
alias cbc="$CLIPBOARDCOPY"
alias cbp="$CLIPBOARDPASTE"

# Internet
alias posttext="curl -F 'sprunge=<-' http://sprunge.us"
alias speedtest="wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip"
alias textme='mailx -s autotext devqqq+autotext@gmail.com'

# Arch
alias pa="pacaur"
alias pm="pacman"
alias spm="sudo pacman"
alias sc="systemctl"
alias ssc="sudo systemctl"
