#!/usr/bin/zsh
# zsh custom aliases

# Use system-specific commands
source $XDG_CONFIG_HOME/zsh/system

# UNIX Abbreviations
alias c='clear'
alias s='sudo'
alias la='ls -A'
alias md='mkdircd'
alias sn="vim +'Simplenote -l'"
alias py='python' # System's default python installation
alias p3="$PYTHON3NAME"
alias p2="$PYTHON2NAME"
alias unix='date "+%s"'
alias view='vim -R'
alias tgz='tar czvf'
alias detgz='tar xvf'
alias untgz='tar xvf'
alias beep="$BEEPCOMMAND"
alias posttext="curl -F 'sprunge=<-' http://sprunge.us"
alias ddg="surfraw duckduckgo"
alias resolve='cd "$(pwd -P)"'

# System tasks
alias reload='source ~/.zshrc'
alias update="$SYSTEMUPDATE"
