#!/usr/bin/zsh
# zsh custom aliases

# Use system-specific commands
source $XDG_CONFIG_HOME/zsh/system

# Abbreviations
alias c='clear'
alias la='ls -A'
alias md='mkdircd'
alias sn="vim +'Simplenote -l'"
alias py='python' # System's default python installation
alias py3="$PYTHON3NAME"
alias py2="$PYTHON2NAME"
alias unix='date "+%s"'
alias view='vim -R'
alias tgz='tar czvf'
alias detgz='tar xvf'
alias untgz='tar xvf'

# System tasks
alias reload='source ~/.zshrc'
alias update="$SYSTEMUPDATE"
alias svim="sudo vim -u $SUDO_USER/.vimrc"
