#!/usr/bin/zsh
# zsh custom functions

# Combines mkdir, cd, pwd
function mkdircd () {
    mkdir -p "$@" &&
    eval cd "\"\$$#\"" &&
    eval echo "Switching to $(pwd)...";
}

# Quickly edit programs in your $PATH
function editex () {
    eval "$EDITOR" "$(which $1)"
}
