#!/usr/bin/zsh
# zsh custom functions

# Use system-specific variables
source $XDG_CONFIG_HOME/zsh/system

# Combines mkdir, cd, pwd
function mkdircd () {
    mkdir -p "$@" &&
    eval cd "\"\$$#\"" &&
    eval echo "Switching to $(pwd)...";
}

# Quickly edit programs in your $PATH
function editex () {
    eval "$EDITOR" "$(which $1)" ${@:2}
}

# Run a locally hosted godoc.org at given port
function hostgodoc () {
    if [ -z $1 ]; then
        PORT="6060"
    else
        PORT="$1"
    fi

    eval "godoc" "-http=:$PORT"
}

# Push to all remotes in git
function pushallremotes () {
    for r in $(git remote); do
        git push "--repo=$r" "$@"
    done
}

function texide () {
    INFILE="$1"
    TEXFILE="$INFILE.tex"
    DVIFILE="$INFILE.dvi"
    PDFFILE="$INFILE.pdf"

    STATUS=0
    while [ $STATUS -eq 0 ]; do
        vim "$TEXFILE"
        let STATUS=$?
        "latex" "$INFILE"
        "bibtex" "$INFILE"
        "latex" "$INFILE"
        "latex" "$INFILE"
        "dvipdf" "$DVIFILE"
        "$OPENCOMMAND" "$PDFFILE"
    done
    return 0
}
