#!/usr/bin/zsh
# zsh program initialization command aliases

uname=`uname`
if [[ $uname == "Darwin" ]]; then;
    alias ls='ls -G'
elif [[ $uname == "Linux" ]]; then;
    alias ls='ls --color=auto'
fi
alias mv="mv -i"
alias cp="cp -i"
alias irssi="irssi --home=$XDG_CONFIG_HOME/irssi"
alias vim="vim -i $XDG_CONFIG_HOME/vim/viminfo -u $XDG_CONFIG_HOME/vim/vimrc"
alias less="less -m -k $XDG_CONFIG_HOME/less/less"
alias ssh="ssh -F $XDG_CONFIG_HOME/ssh/config -o UserKnownHostsFile=$XDG_CONFIG_HOME/ssh/known_hosts"
alias zsh="zsh -ci ZDOTDIR=$XDG_CONFIG_HOME/zsh"
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/conf"
alias screen="screen -T xterm-256color"
