#!/usr/bin/zsh
# zsh settings (e.g. variable assignments, prompts, etc.)

# history files
HISTFILE="$XDG_CONFIG_HOME/zsh/history"
SAVEHIST=1000
HISTSIZE=1000

# vi-style command editing
set -o vi

# git prompt and completion
setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' actionformats \
    '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats       \
    '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'
zstyle ':vcs_info:*' enable git cvs svn

setopt prompt_subst
autoload -U promptinit

function prompt_char {
    git branch >/dev/null 2>/dev/null && echo '± ' && return
    echo ' '
}

function __prompt_char {
    git rev-parse --git-dir >& /dev/null
    if [[ $? == 0 ]]; then
        echo -n '±'
    else
        echo -n ']'
    fi
}

function __git_prompt {
    local DIRTY="%{$fg[yellow]%}"
    local CLEAN="%{$fg[green]%}"
    local UNMERGED="%{$fg[red]%}"
    local RESET="%{$terminfo[sgr0]%}"
    git rev-parse --git-dir >& /dev/null
    if [[ $? == 0 ]]
    then
        echo -n ' -'
        if [[ `git ls-files -u >& /dev/null` == '' ]]
        then
            git diff --quiet >& /dev/null
            if [[ $? == 1 ]]
            then
                echo -n $DIRTY
            else
                git diff --cached --quiet >& /dev/null
                if [[ $? == 1 ]]
                then
                    echo -n $DIRTY
                else
                    echo -n $CLEAN
                fi
            fi
        else
            echo -n $UNMERGED
        fi
        echo -n `git branch | grep '* ' | sed 's/..//'`
        echo -n $RESET
        echo -n '- '
    else
        echo -n ' '
    fi
}

 
if [[ $USER != 'root' ]]; then
    export PS1='$(__prompt_char) '
    export RPS1='%~$(__git_prompt)(%n@%m)'
else
    export PS1='# '
    export RPS1='%~ (%n)'
fi

promptinit
