#!/usr/bin/zsh
# zsh system-specific commands

export PYTHON3NAME='python3'
export PYTHON2NAME='python'
export SYSTEMUPDATE=''
export GOPATH="$HOME/dev/go/"
export BEEPCOMMAND='tput bel'

export PATH="$HOME/bin:$HOME/dev/go/bin/:$PATH"
export EDITOR="vim"
export CLIPBOARDCOPY="xclip -selection clipboard"
export CLIPBOARDPASTE="xclip -o -selection clipboard"
export OPENCOMMAND="xdg-open"
export TRASHCOMMAND="mv -t ~/.local/share/Trash/files"
