#!/usr/bin/zsh
# zsh .conf system initialization

source $XDG_CONFIG_HOME/zsh/system
source $XDG_CONFIG_HOME/zsh/settings
source $XDG_CONFIG_HOME/zsh/initcommands
source $XDG_CONFIG_HOME/zsh/functions
source $XDG_CONFIG_HOME/zsh/aliases
source $XDG_CONFIG_HOME/zsh/events
