#!/usr/bin/env bash
# shell custom aliases

# Use system-specific variables
source "$XDG_CONFIG_HOME/bash/system"

# UNIX
alias c='clear'
alias s='sudo -E'
alias la='ls -A'
alias ll='ls -l'
alias lal='ls -Al'
alias lla='ls -Al'
alias view='vim -R'
alias vimp='vim -p $((git ls-tree --name-only HEAD 2>/dev/null || ls -p .) | awk "! (/^\./ || /\/$/ || /^[mM]akefile$/ )")'
alias vims='vim -S .session.vim'
alias tgz='tar czvf'
alias detgz='tar xvf'
alias untgz='tar xvf'
alias beep="$BEEPCOMMAND"
alias resolve='cd "$(pwd -P)"'
alias lsaf='find . -type f -exec ls {} \;'
alias resume="$RESUMECOMMAND"
alias ukman="loadkeys colemak > /dev/null 2>&1 || setxkbmap us colemak"
alias qwfpgj="loadkeys us > /dev/null 2>&1 || setxkbmap us"

# git
alias gss="git status -s"
alias gst="git status"
alias gd="git diff"
alias gdc="git diff --cached"

# git, in zsh/functions
alias gdw="git-diff-words"
alias gsw="git-show-words"
alias gpa='git-push-all'

# Xorg
alias resolution='xrandr | grep "*" | grep -oe "[0-9]\+x[0-9]\+"'

# versioning
alias py='python' # System's default python installation
alias p3="$PYTHON3NAME"
alias p2="$PYTHON2NAME"

# tool functionality
alias ddg="surfraw duckduckgo"
alias tmuxdr="tmux attach || tmux new"

# iTerm2's `imgcat` doesn't scale for the terminal
alias thumb="convert -resize 600x300 - - | imgcat"

# endrend
alias endrend="python3 $XDG_CONFIG_HOME/bash/endrend.py | mailfmt -w 80"

# System tasks
alias reload='source ~/.zshrc'
alias update="$SYSTEMUPDATE"
alias mt="$TRASHCOMMAND"
alias opn="$OPENCOMMAND"

# Clipboard
alias cbc="$CLIPBOARDCOPY"
alias cbp="$CLIPBOARDPASTE"

# Internet
alias servepwd="python3 -m http.server 8080"
alias posttext="curl -F 'sprunge=<-' http://sprunge.us"
alias speedtest="wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip"
alias textme='mailx -s autotext devqqq+autotext@gmail.com'
alias pubip='wget http://checkip.dyndns.org/ -O - -o /dev/null | cut -d: -f 2 | cut -d\< -f 1'
alias publoc="curl -s http://whatismycountry.com/ | sed -n 's|.*> *\(.*\)</h3>|\1|p'"

# Number systems
alias 2dec="printf '%d\n'"
alias 2hex="printf '%x\n'"

# Time
alias unix='date "+%s"'
alias hext='printf "%x\n" "$(date +%s)"' # or 2hex `unix`

# Arch
alias pa="pacaur"
alias pm="pacman"
alias spm="sudo pacman"
alias sc="systemctl"
alias scu="systemctl --user"
alias ssc="sudo systemctl"

alias pdfcat='gs -dNOPAUSE -sDEVICE=pdfwrite -q -sOutputFile=- -dBATCH'
alias be='bundle exec'

# Android on Linux, uses !apkg android-file-transfer
alias android_mount='aft-mtp-mount /mnt/android'
