#!/bin/sh
# shell custom aliases

# UNIX
alias c='clear'
alias e="$EDITOR"
alias s='sudo -E'
alias se='sudo -e'
alias la='ls -A'
alias ll='ls -l'
alias lal='ls -Al'
alias lla='ls -Al'
alias view="$EDITOR -R"
alias beep="$BEEPCOMMAND"
alias usermount="sudo mount -o fmask=111,dmask=000"
alias resolve='cd "$(pwd -P)"'
alias lsaf='find . -type f -exec ls --color=auto {} \;'
alias resume="$RESUMECOMMAND"
alias unique=$'perl -lne \'$x=$_;if(!grep(/^$x$/,@arr)){print; push @arr,$_ ;}\''

# keyboard layouts
alias ukman="loadkeys colemak > /dev/null 2>&1 || setxkbmap us colemak"
alias qwfpgj="loadkeys us > /dev/null 2>&1 || setxkbmap us"
alias h.ryav="loadkeys dvorak > /dev/null 2>&1 || setxkbmap us dvorak"
alias jsgtmab="loadkeys colemak > /dev/null 2>&1 || setxkbmap us colemak"

# git
alias gss="git status --short"
alias gst="git status"
alias gsw="git switch"
alias gd="git diff"
alias gdc="git diff --cached"
alias gap="git add --patch"

# git, in zsh/functions
alias gdw="git-diff-words"
alias gsw="git-show-words"
alias gpa='git-push-all'

# Xorg
alias resolution='xrandr | grep "*" | grep -oe "[0-9]\+x[0-9]\+"'
alias gpus='lspci -vnnn | perl -lne '"'"'print if /^\d+\:.+(\[\S+\:\S+\])/'"'"' | grep VGA && glxinfo|egrep "OpenGL vendor|OpenGL renderer"'

# versioning
alias py='python' # System's default python installation
alias p3="$PYTHON3NAME"
alias p2="$PYTHON2NAME"

# tool functionality
alias ddg="surfraw duckduckgo"
alias tmuxdr="tmux attach || tmux new"

# iTerm2's `imgcat` doesn't scale for the terminal
alias thumb="convert -resize 600x300 - - | imgcat"

# endrend
alias endrend="python3 $XDG_CONFIG_HOME/bash/endrend.py"

# System tasks
alias reload='source ~/.zshrc'
alias update="$SYSTEMUPDATE"
alias mt="$TRASHCOMMAND"
alias opn="$OPENCOMMAND"
alias efistatus="sudo efibootmgr -v | sed 's:\(.\)\.:\1:g'"
alias lsports="sudo lsof +M -i4"
alias lsport="sudo netstat -tulpn"

# Clipboard
alias cbc="$CLIPBOARDCOPY"
alias cbp="$CLIPBOARDPASTE"

# Internet
alias servepwd='python3 -m http.server $(shuf -i 8001-8999 -n 1) --bind 127.0.0.1'
alias posttext="curl -F 'sprunge=<-' http://sprunge.us"
alias speedtest="wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip"
alias textme='mailx -s autotext devqqq+autotext@gmail.com'
alias myip='wget http://checkip.dyndns.org/ -O - -o /dev/null | cut -d: -f 2 | cut -d\< -f 1'
alias whereami="curl -s http://whatismycountry.com/ | sed -n 's|.*> *\(.*\)</h3>|\1|p' | sed 's|,|, |'"

# Number systems
alias 2dec="printf '%d\n'"
alias 2hex="printf '%x\n'"

# Time
alias unix='date "+%s"'
alias hext='printf "%x\n" "$(date +%s)"' # or 2hex `unix`

# Arch
alias pm="pacman"
alias pp="powerpill"
alias spm="sudo -E pacman"
alias spp="sudo -E powerpill"

# systemd
alias sc="systemctl"
alias jc="journalctl"
alias scu="systemctl --user"
alias jcu="journalctl --user"
alias ssc="sudo -E systemctl"
alias sjc="sudo -E journalctl"

alias pdfcat='gs -dNOPAUSE -sDEVICE=pdfwrite -q -sOutputFile=- -dBATCH'
alias be='bundle exec'

# Android on Linux, uses !apkg android-file-transfer
alias android_mount='aft-mtp-mount /mnt/android'

# Quality hacking music
alias buzzout="cvlc http://www.buzzoutroom.com/listen.pls"

SHRUG='¯\_(ツ)_/¯'
alias shrug="printf %s '$SHRUG' | $CLIPBOARDCOPY && echo '$SHRUG'"

alias jsonp="python -m json.tool"
alias aria='aria2c -c -x 16 -s 16'

alias strict-gcc="gcc -Werror -Wall -Wextra -Wpedantic"

alias monitor-line-in="pactl load-module module-loopback"
alias unmonitor-line-in="pactl unload-module module-loopback"
alias updsrcinfo='makepkg --printsrcinfo > .SRCINFO'
alias whatfs='( while ! findmnt .; do cd ..; done )'
alias occ='ssh cloud.guvernator.net sudo -u http /usr/share/webapps/nextcloud/occ'

alias palette='(x=`tput op` y=`printf %76s`;for i in {0..256};do o=00$i;echo -e ${o:${#o}-3:3} `tput setaf $i;tput setab $i`${y// /=}$x;done)'

alias lxcl='lxc list --format=csv --columns=n'
