#!/usr/bin/env bash
# shell custom aliases

# Use system-specific variables
source "$XDG_CONFIG_HOME/bash/system"

# UNIX
alias c='clear'
alias s='sudo'
alias la='ls -A'
alias ll='ls -l'
alias lal='ls -Al'
alias lla='ls -Al'
alias view='vim -R'
alias vimp='vim -p *'
alias tgz='tar czvf'
alias detgz='tar xvf'
alias untgz='tar xvf'
alias beep="$BEEPCOMMAND"
alias resolve='cd "$(pwd -P)"'
alias lsaf='find . -type f -exec ls {} \;'
alias resume="$RESUMECOMMAND"

# git
alias g="git"
alias gs="git status -s"
alias gss="git status"
alias gd="git diff"
alias gdc="git diff --cached"

# git, in zsh/functions
alias gdw="git-diff-words"
alias gsw="git-show-words"
alias gpa='git-push-all'

# versioning
alias py='python' # System's default python installation
alias p3="$PYTHON3NAME"
alias p2="$PYTHON2NAME"

# tool functionality
alias ddg="surfraw duckduckgo"
alias tmuxdr="tmux attach || tmux new"

# zsh/functions
alias md='mkdircd'
alias edex='editex'

# System tasks
alias reload='source ~/.zshrc'
alias update="$SYSTEMUPDATE"
alias mt="$TRASHCOMMAND"
alias opn="$OPENCOMMAND"

# Clipboard
alias cbc="$CLIPBOARDCOPY"
alias cbp="$CLIPBOARDPASTE"

# Internet
alias posttext="curl -F 'sprunge=<-' http://sprunge.us"
alias speedtest="wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip"
alias textme='mailx -s autotext devqqq+autotext@gmail.com'

# Number systems
alias 2dec="printf '%d\n'"
alias 2hex="printf '%x\n'"

# Time
alias unix='date "+%s"'
alias hext='printf "%x\n" "$(date +%s)"' # or 2hex `unix`

# Arch
alias pa="pacaur"
alias pm="pacman"
alias spm="sudo pacman"
alias sc="systemctl"
alias ssc="sudo systemctl"
