#!/usr/bin/env bash
# shell initialization

# use other config files
set -o vi
source "$XDG_CONFIG_HOME/bash/system"
source "$XDG_CONFIG_HOME/bash/initcommands"
source "$XDG_CONFIG_HOME/bash/functions"
source "$XDG_CONFIG_HOME/bash/aliases"
source "$XDG_CONFIG_HOME/bash/prompt"

# if running interactively...
[[ $- != *i* ]] && return

# add interactive stuff here
