#!/usr/bin/env bash
# initialization command aliases

# OS X is special
uname="$(uname)"
if [[ "$uname" == "Darwin" ]]; then
	alias ls='ls -G'
	alias docker='osxdocker'
elif [[ "$uname" == "Linux" ]]; then
	alias ls='ls --color=auto'
fi

# safe mv/cp
alias mv="mv -i"
alias cp="cp -i"

# not horrible terminal output
alias screen="screen -T $TERM"

# so dc doesn't round everything
# use \dc if piping input
alias dc="dc -e 10k -"

# colored howdoi
alias howdoi="howdoi -c"

# feh uses reasonable defaults
#alias feh="feh -d -."

# autopep8 ignores the dumber pep8 guidelines
# 501: lines less than 80 characters
#   * dumb because this ain't 1970
# 201-2: every list, comprehension or not, has cozy square brackets
#   * dumb because comprehensions should have breathing room
# 301-3: weird arbitrary rules on newlines
#   * dumb because it's hard to tell '\n' from '\n+'
# the rest of the rules are really good; let's stick to those
alias autopep8="autopep8 --ignore 'E501,E201,E202,E301,E302,E303'"

# my own XDG_CONFIG_HOME remedy aliases
alias irssi="irssi --home=$XDG_CONFIG_HOME/irssi"
alias vim="vim -i $XDG_CONFIG_HOME/vim/viminfo -u $XDG_CONFIG_HOME/vim/vimrc"
alias less="less -m -k $XDG_CONFIG_HOME/less/less"
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/conf"

# SSH is especially bad
export SSH_ALIAS_OPTIONS="-F $XDG_CONFIG_HOME/ssh/config -o UserKnownHostsFile=$XDG_CONFIG_HOME/ssh/known_hosts"
alias ssh="ssh $SSH_ALIAS_OPTIONS"
alias scp="scp $SSH_ALIAS_OPTIONS"
export GIT_SSH_COMMAND="ssh $SSH_ALIAS_OPTIONS "$@" 2>/dev/null"

# other XDG_CONFIG_HOME remedies, courtesy <github.com/woegjiub>
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
# Note: gstreamer registry is usually per-arch.
# Any secondary architecture applications should have this exported to a
# different value before launch
# Thankfully, this is only needed for gstreamer0.10; 1.0 has a sane default
export GST_REGISTRY="$XDG_CACHE_HOME/gstreamer/registry-$(uname -m).bin"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export KDEHOME="$XDG_CONFIG_HOME/kde"
export LESSHISTFILE="/dev/null"
export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql/history"
export npm_config_userconfig="$XDG_CONFIG_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export PENTADACTYL_INIT=":source $XDG_CONFIG_HOME/pentadactyl/pentadactylrc"
export PIP_CONFIG_FILE="$XDG_CONFIG_HOME/pip/pip.conf"
export PIP_LOG_FILE="$XDG_DATA_HOME/pip/log"
export PSQLRC="$XDG_CONFIG_HOME/psql/psqlrc"
export PSQL_HISTORY="$XDG_DATA_HOME/psql/history"
export PYLINTHOME="$XDG_DATA_HOME/pylint"
export PYLINTRC="$XDG_CONFIG_HOME/pylint/pylintrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
#export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd.sock"
export TERMINFO="$XDG_CONFIG_HOME/terminfo"
export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"
export VIMPERATOR_INIT=":source $XDG_CONFIG_HOME/vimperator/vimperatorrc"
export VIMPERATOR_RUNTIME="$XDG_CONFIG_HOME/vimperator"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

alias ag="ag -p $XDG_CONFIG_HOME/ag/agignore"
alias mutt="mutt -F $XDG_CONFIG_HOME/mutt/muttrc"
alias ncmpcpp="ncmpcpp -c $XDG_CONFIG_HOME/ncmpcpp/config"
alias startx="startx $XDG_CONFIG_HOME/Xorg/xinitrc"
alias rtorrent="rtorrent -n -o import=$XDG_CONFIG_HOME/rtorrent/conf"

# Disgusting hacks
function sl3(){
	mv {$XDG_DATA_HOME/sqlite3/,~/.}sqlite_history
	sqlite3 "$@"
	mv {~/.,$XDG_DATA_HOME/sqlite3/}sqlite_history
}
