#!/bin/bash
# prompt settings

function __prompt_char() {
    git rev-parse --git-dir >& /dev/null
    if [ "$?" -eq 0 ]; then
        echo -n '±'
    elif [ "$USER" = 'root' ]; then
        echo -n '#'
    else
        echo -n ']'
    fi
}

function __git_prompt() {
    local DIRTY="%{$fg[yellow]%}"
    local CLEAN="%{$fg[green]%}"
    local UNMERGED="%{$fg[red]%}"
    local RESET="%{$terminfo[sgr0]%}"
    git rev-parse --git-dir >& /dev/null
    if [[ $? == 0 ]]
    then
        echo -n ' -'
        if [[ `git ls-files -u >& /dev/null` == '' ]]
        then
            git diff --quiet >& /dev/null
            if [[ $? == 1 ]]
            then
                echo -n "$DIRTY"
            else
                git diff --cached --quiet >& /dev/null
                if [[ $? == 1 ]]
                then
                    echo -n "$DIRTY"
                else
                    echo -n "$CLEAN"
                fi
            fi
        else
            echo -n "$UNMERGED"
        fi
        echo -n `git branch | grep '* ' | sed 's/..//'`
        echo -n "$RESET"
        echo -n '- '
    else
        echo -n ' '
    fi
}

if [ -n "$ZSH_VERSION" ]; then
    setopt prompt_subst
    RPS1='%~$(__git_prompt)(%n@%m)'
else
    shopt -s promptvars
fi

PS1='$(__prompt_char) '

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi
PS1='${debian_chroot:+($debian_chroot)}'"$PS1"
