#!/bin/bash
# system-specific commands

export PYTHON3NAME='python3'
export PYTHON2NAME='python2'
export SYSTEMUPDATE='sudo pacman -Syu'
export BEEPCOMMAND='tput bel'
export TERMINAL='st'
export EDITOR='nvim -p'
export BROWSER='firefox'
export CLIPBOARDCOPY='xsel -bi'
export CLIPBOARDPASTE='xsel -bo'
export OPENCOMMAND='xdg-open'
export TRASHCOMMAND='movetotrash'

if [[ "$EDITOR" =~ '^n?vi.*' ]]; then
  export MANPAGER="$EDITOR -c 'set ft=man' -"
fi
