#!/bin/sh
# system-specific configuration

export SYSTEM_ALIASES_NOT_SET_UP=1
export PYTHON3NAME='python3'
export PYTHON2NAME='python2'
export SYSTEMUPDATE='sudo pacman -Syu'
export BEEPCOMMAND='tput bel'
export TERMINAL='st'
export EDITOR='nvim -p'
export TAG_CMD_FMT_STRING='nvim -c "call cursor({{.LineNumber}}, {{.ColumnNumber}})" "{{.Filename}}"'
export BROWSER='firefox'
export CLIPBOARDCOPY='xsel -bi'
export CLIPBOARDPASTE='xsel -bo'
export OPENCOMMAND='xdg-open'
export TRASHCOMMAND='movetotrash'
export GOTIFY_TOKEN=''
export TTY_USE_TMUX='true'
export START_SWAY='false'

if [[ "$EDITOR" =~ '^n?vi.*' ]]; then
  export MANPAGER="$EDITOR -c 'set ft=man' -"
fi
